<a href="https://colab.research.google.com/github/Atiffaisal/Python/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr2 = np.arange(9,18).reshape(3,3)
arr2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
arr3=arr1+arr2
arr3

array([[18, 20, 22],
       [24, 26, 28],
       [30, 32, 34]])

In [ ]:
arr3 = arr2 * arr1
arr3

array([[ 81, 100, 121],
       [144, 169, 196],
       [225, 256, 289]])

In [ ]:
arr3 = arr2 - arr1
arr3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
A=np.array([[5,6,7],[1,2,3]])
A

array([[5, 6, 7],
       [1, 2, 3]])

In [ ]:

A=np.array([5,6,7])
A

array([5, 6, 7])

***Welcome to Numpy Tutorial with Harry***

---



All done here for Data Science in Numpy
   We already installed Numpy so, let's begin

In [ ]:
import numpy as np

In [ ]:
myarr = np.array([3,6,32,7])
myarr

array([ 3,  6, 32,  7])

In [ ]:
myarr = np.array([[3,6,32,7]],np.int8)
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [ ]:
myarr = np.array([[3,6,32,7]],np.int64)
myarr[0,2]

32

In [ ]:
myarr = np.array([[3,6,32,7]],np.int64)
myarr[0,0]

3

In [ ]:
myarr.shape

(1, 4)

In [ ]:
myarr.dtype

dtype('int64')

###*Making changing in List*
You can see below

In [ ]:
myarr[0,1] =50
myarr

array([[50, 50, 32,  7]])

##**Array Creation : Conversion from other Python Structures**

In [ ]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [ ]:
listarray.dtype

dtype('int64')

In [ ]:
listarray.shape

(3, 3)

In [ ]:
listarray.size

9

In [ ]:
np.array({34,23,23})

array({34, 23}, dtype=object)

###We are going to use **inbuilt function**

In [ ]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
lspace = np.linspace(1,5,12)
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [ ]:
lspace = np.linspace(1,5,5)
lspace

array([1., 2., 3., 4., 5.])

In [ ]:
emp = np.empty((4,6))
emp

array([[4.63835410e-310, 6.76869935e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.30276956e+180],
       [6.00736842e-067, 3.45944506e+097, 7.50275004e-067,
        3.41912407e+126, 4.25223142e+180, 7.48543529e+247],
       [2.32363010e+251, 6.11130817e+223, 2.59903818e-144,
        1.85553304e-051, 3.88586220e-033, 7.17453504e-091],
       [1.88825808e+185, 2.59027906e-144, 1.16442250e-028,
        9.44872517e-143, 6.17582057e-322, 0.00000000e+000]])

In [ ]:
emp = np.empty((2,4))
emp

array([[1.        , 1.57142857, 2.14285714, 2.71428571],
       [3.28571429, 3.85714286, 4.42857143, 5.        ]])

In [ ]:
emp_like = np.empty_like(lspace)
emp_like

array([1., 2., 3., 4., 5.])

In [ ]:
ide = np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape

(45, 45)

In [ ]:
ide.size

2025

In [ ]:
ide = np.identity(5)
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
ide.shape

(5, 5)

In [ ]:
ide.size

25

In [ ]:
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ide.shape

(3, 3)

In [ ]:
ide.size

9

In [ ]:
ide.dtype

dtype('float64')

In [ ]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(99,)

##**Attribute & Method in Numpy**

###NUMPY AXIS
1D = [1,2,3,4,5] .....(Axis 0)
>2D = [[1,2,3],[4,5,6],[7,8,9]] ......(Axis 0, Axis 1)

|_ (x,y)


                 c1, c2, c3
>Axis 0 (r0) [1,  2,  3]
>>(r1)[4,  5,  6]

In [ ]:
X = ([1,2,3],[4,5,6],[7,1, 0])
ar = np.array(X)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.sum(axis=0)

array([12,  8,  9])

In [ ]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [ ]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [ ]:
ar.flat

In [ ]:
for item in ar.flat:
 print(item)

1
2
3
4
5
6
7
1
0


In [ ]:
ar.ndim

2

In [ ]:
ar.size

9

In [ ]:
ar.nbytes

72

In [ ]:
one = np.array([1,3,4,634,2])
one

array([  1,   3,   4, 634,   2])

In [ ]:
one.argmax()

3

In [ ]:
one.argmin()

0

In [ ]:
one.argsort()

array([0, 4, 1, 2, 3])

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.argmin()

8

In [ ]:
ar.argmax()

6

In [ ]:
ar.argmax(axis=0)

array([2, 1, 1])

In [ ]:
ar.argmax(axis=1)

array([2, 2, 0])

In [ ]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [ ]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [ ]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [ ]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

###**Mathematical Operation**

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar2 = np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [ ]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [ ]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [ ]:
ar2-ar

array([[ 0,  0, -2],
       [ 0, -5,  0],
       [ 1,  0,  0]])

In [ ]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [ ]:
ar.sum()

29

In [ ]:
ar.max()

7

In [ ]:
ar.min()

0

###*For finding elements*

In [ ]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [ ]:
np.where(ar<2)

(array([0, 2, 2]), array([0, 1, 2]))

In [ ]:
type(np.where(ar<2))

tuple

In [ ]:
import sys

In [ ]:
Py_ar = [0,4,55,2]
np_ar = np.array(Py_ar)
sys.getsizeof(1) * len(Py_ar)

112

In [ ]:
np_ar.itemsize * np_ar.size

32

In [ ]:
np_ar.tolist()

[0, 4, 55, 2]